import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.*;
import javax.swing.JOptionPane;
public class Login_form extends javax.swing.JFrame {

    /**
     * Creates new form Login_form
     */
    Connection con=null;
    PreparedStatement pst=null;
    PreparedStatement pst1=null;
    ResultSet rs=null;
    public Login_form() {
        initComponents();
        
        Toolkit obl1= getToolkit();
        Dimension obj2= obl1.getScreenSize();
        setLocation(obj2.width/2-getWidth()/2, obj2.height/2-getHeight()/2);
        
        
                
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        box = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        loguser = new javax.swing.JTextField();
        logpass = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        box.setBackground(new java.awt.Color(80, 77, 77));
        box.setForeground(new java.awt.Color(95, 90, 90));
        box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "user", "admin" }));
        getContentPane().add(box, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 440, -1, -1));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setBackground(new java.awt.Color(246, 242, 242));
        jLabel8.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(197, 181, 181));
        jLabel8.setText("Select User");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 410, -1, -1));

        jLabel7.setBackground(new java.awt.Color(254, 254, 254));
        jLabel7.setFont(new java.awt.Font("Rasa Light", 3, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(249, 247, 247));
        jLabel7.setText("TRAVELNATION");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 250, 50));

        jLabel6.setBackground(new java.awt.Color(239, 242, 253));
        jLabel6.setFont(new java.awt.Font("Pagul", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(243, 246, 253));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Sign In");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 70, 180, 60));

        jLabel5.setBackground(new java.awt.Color(247, 248, 254));
        jLabel5.setForeground(new java.awt.Color(250, 251, 255));
        jLabel5.setText("New  here plase signup");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 600, 170, -1));

        jButton2.setBackground(new java.awt.Color(243, 244, 248));
        jButton2.setText("SIGNUP");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 590, 80, 30));

        jButton1.setBackground(new java.awt.Color(243, 244, 248));
        jButton1.setText("LOGIN");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 500, 90, -1));

        loguser.setBackground(new java.awt.Color(57, 64, 89));
        loguser.setForeground(new java.awt.Color(236, 240, 249));
        jPanel2.add(loguser, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 250, 300, -1));

        logpass.setBackground(new java.awt.Color(57, 64, 89));
        logpass.setForeground(new java.awt.Color(230, 233, 241));
        jPanel2.add(logpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 350, 300, -1));

        jLabel4.setFont(new java.awt.Font("Tlwg Typo", 1, 23)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(252, 247, 245));
        jLabel4.setText("Password");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 300, 250, 40));

        jLabel3.setFont(new java.awt.Font("TlwgTypewriter", 1, 23)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(239, 238, 237));
        jLabel3.setText("Username");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 200, 280, 40));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon("/home/shahil/Pictures/Wallpapers/259-1080x1350.jpeg")); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 620));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon("/home/shahil/Pictures/java/20200527_165547.jpg")); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, 380, 620));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      
        // TODO add your handling code here:
        Regform r=new Regform();
        r.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      
        try {
            String query="SELECT * FROM `Login_details` WHERE loguser=? and logpass=? and usertype=?";
            String q1="UPDATE `Current` SET Userid=?";
            con =DriverManager.getConnection("jdbc:mysql://localhost:3307/user_login","root","");
            pst = con.prepareStatement(query);
            pst.setString(1, loguser.getText());
             pst.setString(2, logpass.getText());
              pst.setString(3, String.valueOf(box.getSelectedItem()));
              rs=pst.executeQuery();
              pst1 = con.prepareStatement(q1);
              pst1.setString(1, loguser.getText());
             // pst1.setInt(2,1);
              pst1.executeUpdate();
              
             if(rs.next()){
                 JOptionPane.showMessageDialog(this, "Logging in as "+ rs.getString("usertype"));
                if(box.getSelectedIndex()==0){
                    User u= new User();
                    u.setVisible(true);
                    this.setVisible(false);
                    
                }
                else{
                   Admin_panel a=new Admin_panel();
                    a.setVisible(true);
                    this.setVisible(false);
                }
             }
                else{
                       JOptionPane.showMessageDialog(this, "userid and password does not match");
                        }
             
             
              
         
            
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }


        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login_form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> box;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField logpass;
    private javax.swing.JTextField loguser;
    // End of variables declaration//GEN-END:variables
}
